# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='route_interest',
            field=models.ManyToManyField(blank=True, related_name='interested_customers', to='db.Route'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='route_subscribe',
            field=models.ManyToManyField(blank=True, related_name='subscribed_customers', to='db.Route'),
        ),
    ]
